controller_list:
  - name: fake_arm_controller_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_controller_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_gripper_left
      - joint_gripper_right
initial:  # Define initial robot poses per group
  - group: arm_controller
    pose: initial_pose
  
  - group: gripper_controller
    pose: open